// Version labels follow Eledger's scheme: first entry is v1.0, each
// subsequent entry is +0.1, up to a max of x.10 — the entry after any x.10
// rolls to (x+1).0. One entry per release (not per commit — a release here
// can bundle several commits; historic pre-2026 releases are summarized in
// batches rather than reconstructed release-by-release). Oldest first
// below (rendered newest-first in the UI).
export const CHANGELOG = [
  {
    v: "v1.0", date: "2024–2025",
    title: "Early flight, prayer, and NOTAM features",
    notes: [
      "NEW: METAR/TAF flight category + wind severity colour coding",
      "NEW: METAR/TAF plain-English decode toggle",
      "NEW: Imsak & Sunrise styled as reference times",
      "NEW: Prayer times auto-refresh after midnight",
      "NEW: Launcher / tabs / grouped navigation styles",
      "NEW: Settings responsive tabbed UI (sheet on mobile, modal on desktop)",
      "NEW: Per-tab error boundaries + code-split lazy loading",
      "FIX: Qibla compass — rotate with device, true North tracking",
      "NEW: NOTAM module — autorouter.aero OAuth proxy",
      "NEW: Vitest unit tests (92 tests)",
    ],
  },
  {
    v: "v1.1", date: "2025",
    title: "Scientific calculator and NOTAM revamp",
    notes: [
      "NEW: Scientific calculator — expression engine + unit converter",
      "NEW: Flight tab — clock-time mode (dep/arr) with UTC/local toggle",
      "NEW: Dhuha prayer time added",
      "NEW: NOTAM revamped — grouped by location, role-coloured, filterable",
      "NEW: Full OurAirports dataset (worldwide ICAO coverage)",
      "FIX: Day-shifted prayer times from UTC cache key",
      "FIX: Reset All no longer leaves stale fields",
    ],
  },
  {
    v: "v1.2", date: "Jun 2026",
    title: "NOTAM persistence and prayer fixes",
    notes: [
      "FIX: NOTAM inputs & results persist to localStorage for offline viewing",
      "FIX: Show \"No NOTAMs available\" per location when API returns nothing",
      "FIX: Dhuha styled as full prayer row; greys out with ✓ after time passes",
      "FIX: UTC/Z toggle relabelled to UTC / ZULU",
    ],
  },
  {
    v: "v1.3", date: "Jun 2026",
    title: "Settings reorganized, Duty Log module added",
    notes: [
      "NEW: Settings reorganised into Appearance / Navigation / Tools / Prayer / About",
      "NEW: Theme AUTO mode — follows system light/dark in real time",
      "NEW: Five accent colours: teal, amber, cyan, violet, green",
      "NEW: Card style: flat / raised / glass",
      "NEW: Global clock format — one 12/24h setting for all clocks",
      "NEW: Unit preferences (temp, wind, visibility, altitude, pressure)",
      "NEW: Export / import settings as JSON; reset settings to defaults",
      "NEW: Haptic strength, dashboard widget toggles, confirm-before-reset",
      "FIX: Auto-detect app updates without manual check",
      "NEW: Flight Duty Log — new module for logging sectors, fuel, times, ENG OUT data, crew, and per-sector remarks with offline persistence",
    ],
  },
  {
    v: "v1.4", date: "Jun 2026",
    title: "Offline reliability and fix pass",
    notes: [
      "NEW: Currency: all pairs available offline — rates cached on first use, auto-refreshed on open",
      "FIX: Currency: offline shows last downloaded rates with age and effective date (3-tier fallback)",
      "FIX: NOTAM: offline viewing after restart now works correctly",
      "FIX: METAR: weather tokens no longer appear garbled in plain-English decode",
      "FIX: METAR: history-window setting change now syncs to the active session immediately",
      "FIX: METAR: auto-refresh only fires when flight routes are entered",
      "FIX: Prayer: city search and GPS geocoding comply with OpenStreetMap ToS",
      "FIX: Prayer: GPS location no longer re-read on every render (faster startup)",
      "FIX: Prayer: offline mode no longer auto-switches to the flight tab",
      "FIX: FTL: time label corrected to \"LOCAL TIME AT REPORTING\"",
      "FIX: FTL: helicopter option greyed out with tooltip (tables not yet available)",
      "FIX: FTL: DST ambiguity in flight-time UTC conversion corrected (two-pass)",
      "FIX: Scientific calculator: scientific notation (1e-3, 2.5e6) now evaluates correctly",
      "FIX: Settings: import validates structure before applying; malformed files rejected",
      "FIX: Settings: keyboard navigation in settings panel corrected",
      "FIX: Dashboard: next-prayer widget reads live times (no stale display after midnight)",
      "FIX: Update checker: interval and visibility listener cleaned up on unmount",
      "FIX: Error boundary: label updated to \"DEBUG INFO — copy when reporting a bug\"",
      "FIX: Changelog badges: Android WebView compatibility improved",
      "FIX: Service worker: removed duplicate registration that conflicted with PWA plugin",
    ],
  },
  {
    v: "v1.5", date: "Jun 2026",
    title: "5-day prayer times and timezone-aware clock mode",
    notes: [
      "NEW: Prayer: 5-day prayer times — day selector strip shows today + 4 days, computed offline instantly",
      "FIX: Prayer: next prayer widget now counts down to next day's Fajr after Isha (no more disappearing)",
      "FIX: Prayer: launcher style always opens dashboard home, ignoring remembered last tab",
      "NEW: Flight: clock mode local time is timezone-aware — dep/arr interpreted in airport's own timezone",
      "NEW: Flight: live flight time banner shows total duration + UTC offsets as you type",
      "NEW: Flight: swap button (⇄) swaps dep/dest for quick return-leg entry",
      "NEW: Flight: cabin direction dial updated to narrow-body airliner silhouette",
      "FIX: Flight: departure label updated to DEP TIME (ETD); disclaimer updated",
      "FIX: Airport database: 4,906 airports; 4,345 now carry IANA timezone data",
    ],
  },
  {
    v: "v1.6", date: "Jun 2026",
    title: "Flight prayer timeline",
    notes: [
      "FIX: Flight: clock-mode local-time elapsed calc anchored to the wrong calendar date, could show 100% complete shortly after a UTC+8 morning departure",
      "NEW: Flight: in-flight prayer timeline — plots every Imsak/Fajr/Sunrise/Dhuhr/Asr/Maghrib/Isha along the route (replaces the single position snapshot), including repeats on long-haul flights",
      "NEW: Flight: DEP TIME / ARR TIME toggle — read the same in-flight prayer moment on either the departure or arrival watch",
      "NEW: Flight: current-position card with manual refresh button; auto-refreshes when returning to the tab or the app is foregrounded",
      "FIX: Flight: timeline rows now spaced proportionally to elapsed time so the progress line lines up exactly with the current-position marker",
    ],
  },
  {
    v: "v1.7", date: "Jun 2026",
    title: "Per-module reset buttons and Duty Log grouping",
    notes: [
      "FIX: Header banner color now updates correctly in light mode",
      "FIX: Removed swipe gesture navigation (was triggering unintended tab changes)",
      "FIX: Flight prayer tab coordinates now shown in N/E degree-minute notation",
      "NEW: Per-module RESET buttons (Calculator, METAR/TAF, NOTAM, Interpolation, EDTO, Currency, FTL, Flight prayer) replace the old global \"Reset All\", each confirming before clearing",
      "NEW: Duty Log: past entries auto-group into collapsible year › month banners; current month and undated entries stay flat",
      "NEW: Duty Log: disclaimer that logs are stored on-device only and are not synced",
      "NEW: Calculator: new Volume, Area, Pressure, Time, and Angle conversion categories, plus a Fuel mass/volume converter with a density input",
      "NEW: Calculator: unit converter moved out of Scientific mode into its own CONVERT mode",
      "NEW: METAR/TAF and NOTAM: swap (⇄) button for departure/arrival fields",
      "FIX: Combined Calculator and FTL: RESET button no longer clips into the row below it",
    ],
  },
  {
    v: "v1.8", date: "Jun 2026",
    title: "Duty Log backup and sync",
    notes: [
      "NEW: Duty Log: Backup & Sync — back up your logs to the cloud and restore them on another device using a short anonymous code (no account required)",
      "NEW: Duty Log: Backup & Sync moved into Settings, with a status card showing last-synced time and a BACKUP / RESTORE tab switcher",
      "NEW: Duty Log: generate a QR code for your backup code, or scan one with the camera to restore — manual code entry still works as a fallback",
      "FIX: Settings: removed the JSON export/import and reset-to-defaults section, superseded by Duty Log Backup & Sync",
    ],
  },
  {
    v: "v1.9", date: "Jun 2026",
    title: "Duty Log backup and sync redesign",
    notes: [
      "NEW: Duty Log: Backup & Sync redesign — each device claims ownership of a sync code; only the owner can push, and restoring/importing transfers ownership to the new device",
      "NEW: Duty Log: per-entry sync status on each log card (SYNCED dot or a one-tap ○ SYNC), plus a prompt to sync right after creating a new log",
      "NEW: Duty Log: new \"Have a code? Enter here to view it\" panel — view another device's backed-up logs read-only, with an optional confirm-gated import that overwrites local logs and transfers ownership",
      "NEW: Settings: sync code & QR now always visible once created, instead of hidden behind a tab; restore now requires a two-tap in-place confirmation instead of a browser dialog",
    ],
  },
  {
    v: "v1.10", date: "Jun 2026",
    title: "Animated launch splash",
    notes: [
      "NEW: Animated splash screen on launch — the C mark fades in, the chamfered double-line frame draws on around it, then the CLAUDEBORNE wordmark fades in, before settling into the app",
    ],
  },
  {
    v: "v2.0", date: "Jun 2026",
    title: "FTL Calculator: CAD 1901 compliance audit",
    notes: [
      "FIX: FTL: standby Max FDP now correctly compares the standby-start time band against the report-time band and uses whichever is more limiting (Ch. 2.9.1) — was previously ignoring the standby-start band entirely",
      "NEW: FTL: added Delayed Reporting (Ch. 2.7) — models planned vs actual report time, with the correct <4h vs ≥4h delay rules",
      "NEW: FTL: added Positioning (Ch. 2.8) — FDP now correctly commences at the positioning report time instead of the flight's own report time",
      "NEW: FTL: added standby location (Home / Airport) and the home ≤2h-notice exception (Ch. 2.9.1/2.9.2) — airport standby shows Max FDP immediately from standby start, with FDP Expires pending the actual call-out time",
      "NEW: FTL: added \"Reduced Preceding Rest\" toggle, gating the Split Duty prohibition, PIC discretion restriction, and mandatory CAAM reporting rules (Ch. 2.13.4 / 2.15.3 / 2.15.4)",
      "NEW: FTL: cabin crew can now report at a different time than flight crew (Ch. 2.21.2a) — the table band uses flight crew's report time, the FDP clock uses cabin crew's own",
      "NEW: FTL: result panel now distinguishes pending inputs (amber) from mandatory CAAM reporting and rule violations (red)",
      "FIX: FTL: PIC discretion before/after the last sector now caps correctly at 2h/3h using the real sector count, not the long-range-modified count",
      "FIX: FTL: long range sector boundary corrected to trigger only above 7h (was triggering at exactly 7h)",
      "FIX: FTL: single-pilot operations no longer allow \"Not Acclimatised\" — CAD 1901 defines no such table for single-pilot ops",
    ],
  },
  {
    v: "v2.1", date: "Jul 2026",
    title: "Traffic, Flight Schedules and SIGMET tabs",
    notes: [
      "NEW: New Traffic tab — live ADS-B aircraft tracking via SkyLink, radar map, center picker (ICAO/GPS/POPULAR), 250/500NM range, multi-callsign/registration/flight# search, Show/Hide Fields with select-all, greys out and auto-resumes with connectivity",
      "NEW: Traffic: Aircraft Lookup card now shows operator, country, engine type, wake category, cruise speed, range, MTOW, service ceiling, wingspan, length, and an airline logo",
      "NEW: Added Flight Schedules tab — SkyLink arrivals/departures board per airport with date/time-range filtering, pagination, and terminal/gate/status lookup",
      "NEW: Added SIGMET tab (aviationweather.gov international feed, reuses NOTAM's FIR/route detection)",
      "NEW: METAR/TAF and NOTAM now alternate between SkyLink and the existing sources (aviationweather.gov / autorouter.aero) by UTC even/odd day, with silent fallback and a source chip showing what was actually used",
      "NEW: METAR/TAF: each role card gets a collapsed RUNWAYS section — headwind/crosswind/tailwind for every runway against that card's own latest wind",
      "FIX: Runways panel no longer gets stuck on a stale airport or stuck in an error state after an abort mid-fetch",
      "FIX: Sched Dep/Arr times showing blank — AeroDataBox separates date/time with a space, not \"T\" as documented",
      "NEW: Calculator: Basic/Scientific/Time now dynamically scale to always fit the viewport without scrolling, growing to fill tablet screens instead of just shrinking",
      "NEW: Calculator: unit converter revamped — bidirectional FROM/TO inputs, tappable unit chips with category icons, replacing dropdowns",
      "FIX: Time calculator expression history was clearing on equals instead of showing the completed line; Scientific now has the same history",
      "NEW: Radar-sweep loading animation on manual METAR/TAF and NOTAM fetches",
      "NEW: Duty Log: scanning a QR code matching your sync-code format now auto-loads it, with a scan-viewfinder loading animation",
      "FIX: NOTAM: real API error detail now shown instead of a bare HTTP status code",
      "FIX: NOTAM: \"COPY FROM METAR/TAF\" no longer leaves stale FIR entries behind",
      "NEW: Flight prayer timeline: added a UTC TIME option alongside DEP/ARR TIME",
      "FIX: Settings: removed redundant \"new version available\" badge",
    ],
  },
  {
    v: "v2.2", date: "Jul 2026",
    title: "Traffic tab rebuilt as flight-status lookup",
    notes: [
      "NEW: Traffic tab rebuilt as a lean flight-status lookup — search a callsign or flight number, see status/route/sched vs actual-or-estimated arrival/delay/arrival terminal/gate. Dropped the ADS-B radar plot, GPS/ICAO center + range picker, and aircraft-spec lookup (manufacturer/wingspan/MTOW/engine/cruise speed/airline logo) — none of it served the tab's actual job",
      "NEW: Traffic: View settings panel (default lean, View all toggle) with sectioned Live position/Departure/Arrival detail cards, an airline logo field (via SkyLink, since AeroDataBox's flight data has none), and a SkyLink ADS-B cross-check for live position when AeroDataBox has none",
      "NEW: Traffic: every departure/arrival airport now defaults to showing scheduled + actual departure, scheduled + actual-or-estimated arrival, both legs' terminal/gate, and arrival delay — the ten data points this tab now guarantees by default",
      "NEW: Traffic: status now cross-checks the provider's label against the flight's own timestamps and overrides it only on a direct contradiction (e.g. \"Arrived\" while the arrival time is still hours away) — fixes a real case where a still-airborne flight showed as landed",
      "NEW: Traffic: every displayed time now shows its UTC offset (e.g. \"12:15 +05:30\") alongside the departure/arrival airport it belongs to, so departure- and arrival-local times are never mistaken for the same clock",
      "DEP: Removed the Flight Schedules tab — airport-board browsing is retired; Traffic's flight-number search is now the only way to check a flight, with a fuller default detail card taking over what Schedules' terminal/gate popup used to show",
      "NEW: Traffic: search now also accepts an aircraft registration (e.g. 9M-MXA), not just a flight number — tries flight number first, falls back to registration on a miss. A registration matching multiple sectors flown that day shows a picker with the most relevant leg pre-selected and marked LIVE only when its departure is actually confirmed, not just scheduled; tap Confirm to load it",
      "FIX: Traffic: search box no longer shows two redundant instructions (placeholder + idle-state text) — placeholder now reads \"Flight number or registration\" instead of the confusing \"callsign or flight number\" pairing",
    ],
  },
  {
    v: "v2.3", date: "Aug 2026",
    title: "Calculator, Converter and SIGMET polish",
    notes: [
      "NEW: Calculator: Basic/Scientific/Time/Convert rebuilt to fill available screen space using CSS flexbox/grid instead of a JS viewport-measuring scale — removes empty margins in both portrait and landscape, and can no longer overflow into a scrollbar the way the JS approach occasionally did",
      "NEW: Calculator: Basic/Time equals moved from a full-width bottom bar to a corner button spanning the last two rows, freeing a row for a bigger display; Scientific's function keys now sit in their own left-hand column instead of stacking above the numpad",
      "NEW: Calculator: numpad rearranged to match a physical numpad's layout — operators sit one per digit row, equals spans the bottom two rows next to 1-2-3 and 0/.",
      "NEW: Calculator: digit, equals, backspace, decimal, and clear buttons are now all the same 26px size — backspace/decimal/clear used to be visibly smaller than the rest",
      "NEW: Converter: FROM/TO cards now sit side by side instead of stacked, with the swap button between them",
      "FIX: Settings icon resized to a fixed 32×32px box (16px glyph) on desktop, 42×42px (16px glyph) on mobile — was a single inconsistent size at all widths",
      "DEP: Removed the header search tool (icon + search-everything overlay) — unused",
      "NEW: SIGMET: added Destination Alternates and Enroute Alternates fields plus a Copy from METAR/TAF button; auto-detect FIRs now scans all of them — matches NOTAM's route entry",
    ],
  },
  {
    v: "v2.4", date: "Aug 2026",
    title: "Duty Log CORS fix",
    notes: [
      "FIX: Duty Log sync endpoint now sends CORS headers for claudeborne.my — enables eLogbook's new Duty Log Link feature to read your synced entries",
    ],
  },
  {
    v: "v2.5", date: "Aug 2026",
    title: "B737 Performance tab",
    notes: [
      "NEW: New B737 PERFORMANCE tab — combines EDTO and two new calculators as sub-modes in one tab. EDTO is no longer a separate top-level tab",
      "NEW: Go-Around Climb Gradient (ENG INOP) — single-engine go-around climb gradient for Flaps 15/Gear Up, covering NG (CFM56-7B24, CFM56-7B26 FAA/JAA) and MAX (LEAP-1B25, LEAP-1B27). Full report: reference/weight-adjusted/speed-adjusted gradient plus packs-off/anti-ice/icing corrections, digitized from the FCOM Performance Dispatch pages. Speed is a VREF40+X dropdown matching the table's own published values; fields ordered OAT → Pressure Altitude → Weight → Speed to match the calc sequence",
      "NEW: Quick Turnaround Limit Weight — landing-weight limit for a quick turnaround (Flaps 40), covering NG Category C/Steel and Category N/Carbon brakes plus MAX (single table, no brake-type split). Adjusts for runway slope and wind component (asymmetric rates — favorable vs unfavorable direction), then gives a WITHIN LIMIT / EXCEEDS LIMIT verdict against your actual landing weight, with the manual's wait-time/brake-temperature/BTMS guidance shown when exceeded. Fields ordered Landing Weight → OAT → Pressure Altitude → Slope → Wind",
      "NEW: New icons for B737 Performance and its three sub-tabs (EDTO, Go-Around, Quick Turnaround), in both mono and color icon sets",
    ],
  },
  {
    v: "v2.6", date: "Aug 2026",
    title: "Duty Log and Interpolation fixes",
    notes: [
      "NEW: Duty Log: view-code entry remembers your last 5 codes as tappable chips instead of requiring retyping",
      "FIX: Interpolation: table header/cell inputs now show a visible box instead of being indistinguishable from static chrome until clicked",
    ],
  },
  {
    v: "v2.7", date: "Sep 2026",
    title: "Malaysia Airports gate finder",
    notes: [
      "NEW: Malaysia Airports — new gate finder tab (departure/arrival board lookup by airport/day/flight/city/airline), with a large boxed gate number, colored status pill, airline logo, and a collapsible codeshare list per card",
      "NEW: Malaysia Airports: gate box gets its own go/hurry/missed traffic-light color, independent of the overall flight status",
      "FIX: Malaysia Airports: status colors corrected to match the API's real per-leg vocabulary (departures track check-in → gate, arrivals track baggage) after real data showed most flights falling through to a gray default",
    ],
  },
  {
    v: "v2.8", date: "Sep 2026",
    title: "Flight Briefing",
    notes: [
      "NEW: Flight Briefing — a ✈ BRIEFING button in METAR/TAF, NOTAM and SIGMET opens a combined overlay (METAR/TAF + NOTAM + SIGMET) built from that module's own route input, so dep/arr/alternates/enroute never has to be re-typed across modules. METAR/TAF has no FIR concept of its own, so the overlay auto-detects route FIRs the same way NOTAM/SIGMET already do",
      "NEW: Briefing: route map with real coastlines and a great-circle route curve, plotting departure/arrival, alternates and enroute alternates by actual lat/lng, replacing the earlier summary cards",
      "NEW: Briefing: NOTAMs now also fetched and shown per route FIR (airspace/oceanic notices), not just per airport",
      "NEW: Briefing: opening it now also auto-populates and fetches METAR/TAF, NOTAM and SIGMET's own standalone caches from the same fetch (no extra API calls), so opening any of the 3 modules directly afterward shows the same route and data already loaded",
      "NEW: Briefing: persists across reloads and offline reopens like the other modules; closing (✕/Escape/backdrop) now pauses instead of discarding, so an offline reopen still finds the cached data; a \"Resume Briefing\" pill brings it back with no refetch",
      "NEW: Briefing: per-airport NOTAMs sorted runway/taxiway/obstacle/navaid first and capped at 5, each entry clamped to 5 lines, with a link to the full NOTAM tab for anything longer",
      "FIX: Briefing: wrapped in the app's error boundary so a render crash on real (non-mock) NOTAM/METAR data shows a retryable error card instead of white-screening the whole app",
      "FIX: PWA offline caching added for /api/notam, /api/skylink and /api/isigmet — NOTAM and SIGMET now survive offline the same way METAR/TAF already did",
      "NEW: RESET buttons — now ask whether to reset just the current module or all 3 (METAR/TAF, NOTAM, SIGMET); either choice also clears the Flight Briefing cache",
    ],
  },
  {
    v: "v2.9", date: "Sep 2026", current: true,
    title: "Briefing fixes, reset dialogs, and a World Time map",
    notes: [
      "FIX: METAR/TAF, NOTAM and SIGMET now show a Briefing's fetched results the moment the overlay closes — previously needed leaving and returning to the tab to see the synced data",
      "NEW: RESET dialogs simplified — modules with no related caches (Calculator, Interpolation, EDTO, Go-Around, Quick Turnaround, Currency, FTL, Qiblat & Solat) now get a single-button \"CONFIRM RESET\"; METAR/TAF, NOTAM and SIGMET keep the module/all-3 scope choice, reworded to match",
      "NEW: Briefing: each section (Departure & Arrival, Destination Alternates, Enroute Alternates, Notams, Sigmets) now has its own title colour and background tint for faster visual scanning",
      "FIX: Duty Log: new entries start with 6 blank crew rows instead of 4",
      "NEW: World Time — a world map plotting Local and every saved clock by city, with a live day/night shading band; tap a pin to jump to and highlight that clock's card",
    ],
  },
]
